Base/src/Entity/User/Absence.php
<?php

namespace App\Entity\User;

use App\Entity\AbstractEntity;
use Doctrine\ORM\Mapping as ORM;
use \DateTime;
use App\Entity\User\User;
use App\Repository\AbsenceRepository;

#[ORM\Entity(repositoryClass: AbsenceRepository::class)]
class Absence extends AbstractEntity
{

    #[ORM\Column(type: "datetime")]
    private DateTime $fromDate;

    #[ORM\Column(type: "datetime")]
    private DateTime $toDate;

    const ABSENCE_TYPE_LIST = [
        'RTT' => 'RTT',
        'UNPAYED' => 'UNPAYED',
        'DISEASE' => 'DISEASE',
        'FAIR' => 'FAIR'
    ];

    #[ORM\Column(type: "string")]
    private string $type;

    /**
     * @var User
     */
    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'absences', cascade: ['persist', 'remove'])]
    private User $user;

    public function getFrom(): DateTime
    {
        return $this->fromDate;
    }

    public function setFrom(DateTime $date, string $moment = 'AM'):void
    {
        if($moment === 'AM') {
            $hour = '00:00';
        } else {
            $hour = '02:00';
        }

        $this->fromDate = DateTime::createFromFormat('d/m/Y h:i A', $date->format('d/m/Y') . " ". $hour ." " . $moment);
    }

    public function getTo(): DateTime
    {
        return $this->toDate;
    }

    public function setTo(DateTime $date, string $moment = 'AM'): void
    {
        if($moment === 'AM') {
            $hour = '00:00';
        } else {
            $hour = '02:00';
        }

        $this->toDate = DateTime::createFromFormat('d/m/Y h:i A', $date->format('d/m/Y') . " ". $hour ." " . $moment);
    }

    public function isOff(string $dateString, string $momentKey = 'AM'): bool
    {
        $date = DateTime::createFromFormat('d/m/Y h:i A', $dateString . " " . ($momentKey === 'AM'? '00:00' : '02:00') . " " . $momentKey);
        
        return $date >= $this->getFrom() && $date <= $this->getTo();
    }

    public function setUser(User $user)
    {
        $this->user = $user;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType(string $type)
    {
        $this->type = $type;
    }
}

Base/src/Entity/User/AbstractDayPart.php
<?php

namespace App\Entity\User;

use Doctrine\ORM\Mapping as ORM;
use App\Entity\AbstractEntity;

#[ORM\MappedSuperclass]
abstract class AbstractDayPart extends AbstractEntity
{
    /**
     * @var int
     */
    #[ORM\Column(type: 'integer')]
    private int $startHour = 14;

    /**
     * @var int
     */
    #[ORM\Column(type: 'integer')]
    private int $startMinutes = 0;

    /**
     * @var int
     */
    #[ORM\Column(type: 'integer')]
    private int $endHour = 18;

    /**
     * @var int
     */
    #[ORM\Column(type: 'integer')]
    private int $endMinutes = 0;

    /**
     * @var bool
     */
    #[ORM\Column(type: 'boolean')]
    private bool $working = true;

    /**
     * @return int
     */
    public function getStartHour(): int
    {
        return $this->startHour;
    }

    /**
     * @param int $startHour
     * @return void
     */
    public function setStartHour(int $startHour): void
    {
        $this->startHour = $startHour;
    }

    /**
     * @return int
     */
    public function getStartMinutes(): int
    {
        return $this->startMinutes;
    }

    /**
     * @param int $startMinutes
     * @return void
     */
    public function setStartMinutes(int $startMinutes): void
    {
        $this->startMinutes = $startMinutes;
    }

    /**
     * @return int
     */
    public function getEndHour(): int
    {
        return $this->endHour;
    }

    /**
     * @param int $endHour
     * @return void
     */
    public function setEndHour(int $endHour): void
    {
        $this->endHour = $endHour;
    }

    /**
     * @return int
     */
    public function getEndMinutes(): int
    {
        return $this->endMinutes;
    }

    /**
     * @param int $endMinutes
     * @return void
     */
    public function setEndMinutes(int $endMinutes): void
    {
        $this->endMinutes = $endMinutes;
    }

    /**
     * @return bool
     */
    public function isWorking(): bool
    {
        return $this->working;
    }

    /**
     * @param bool $working
     * @return void
     */
    public function setWorking(bool $working): void
    {
        $this->working = $working;
    }

    public function getHoursUsed()
    {
        if(!$this->isWorking()) {
            return 0;
        }
        $minutesEnd = strtotime($this->endHour . ':' . $this->endMinutes . ":00");
        $minutesStart = strtotime($this->startHour . ':' . $this->startMinutes . ":00");

        $diff = $minutesEnd - $minutesStart;

        return $diff / 60 /60;
    }
}

Base/src/Entity/User/Schedule.php
<?php

namespace App\Entity\User;

use App\Entity\AbstractEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\User\User as targetUser;
use \DateTime;
use Doctrine\Common\Collections\Criteria;

#[ORM\Entity()]
class Schedule extends AbstractEntity
{

    /**
     * @var User
     */
    #[ORM\ManyToOne(inversedBy: 'schedule', targetEntity: targetUser::class, cascade: ['persist', 'remove'])]
    private User $user;

    /**
     * @var DateTime
     */
    #[ORM\Column(type: "datetime")]
    private DateTime $startAt;

    #[ORM\Column(type: "boolean")]
    private bool $active = true;

    const WEEK_DAYS = [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday'
    ];

    /**
     * @var User
     */
    #[ORM\OneToMany(mappedBy: "schedule", targetEntity: Day::class, cascade: ['persist', 'remove'])]
    private Collection $days;

    /**
     * @return void
     */
    public function __construct(User $user)
    {
        $days = new ArrayCollection();

        $this->startAt = new DateTime();
        $this->user = $user;

        $i = 1;
        foreach ($this::WEEK_DAYS as $dayName) {
            $day = new Day($dayName, $i, $this);
            $days->add($day);

            $i++;
        }

        $this->days = $days;
    }

    /**
     * @return User
     */
    public function getUser(): User
    {
        return $this->user;
    }

    /**
     * @param User $user
     * @return void
     */
    public function setUser(User $user): void
    {
        $this->user = $user;
    }

    /**
     * @return Collection
     */
    public function getDays(): Collection
    {
        return $this->days;
    }

    /**
     * @param Collection $days
     * @return void
     */
    public function setDays(Collection $days): void
    {
        $this->days = $days;
    }

    public function getStartAt(): DateTime
    {
        $this->startAt->modify('00:00');
        return $this->startAt;
    }

    public function setStartAt(DateTime $date): self
    {
        $date->modify('00:00');

        $this->startAt = $date;

        return $this;
    }

    public function isActive(): bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getWorkingHours(string $dayName)
    {
        $criteria = Criteria::create()
            ->andWhere(Criteria::expr()->eq('name', $dayName));

        return $this->days->matching($criteria)->current();
    }

    /**
     * Calculate worked total hours per week
     */
    public function getHoursPerWeek(): int
    {
        $hours = 0;

        foreach ($this->days as $day) {
            if ($day->isHourValid()) {
                $dayHours = $day->getMorning()->getHoursUsed() + $day->getAfternoon()->getHoursUsed();

                $hours += $dayHours;
            }
        }

        return $hours;
    }
}

Base/src/Entity/User/User.php
<?php

namespace App\Entity\User;

use App\Entity\AbstractEntity;
use App\Entity\CalendarEvent;
use App\Entity\Company;
use App\Entity\Message;
use App\Entity\TchatRoom;
use App\Entity\User\Team;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use App\Entity\Work\Assignation;
use App\Entity\User\Absence;
use App\Repository\UserRepository;
use App\Entity\User\Security\PasswordResetting;
use \DateTime;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use App\Service\FileUploader;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['userName'], message: 'There is already an account with this userName')]
class User extends AbstractEntity implements UserInterface, PasswordAuthenticatedUserInterface
{

    /**
     * @var string
     */
    #[ORM\Column(type: 'string', length: 255, unique: true)]
    private string $userName = '';

    /**
     * @var string
     */
    #[ORM\Column(type: 'string', length: 255)]
    private string $firstName = '';

    /**
     * @var string
     */
    #[ORM\Column(type: 'string', length: 255)]
    private string $lastName = '';

    /**
     * @var string
     */
    #[ORM\Column(type: 'string', length: 255, unique: true, nullable: false)]
    private string $email = '';

    /**
     * @var string
     */
    #[ORM\Column(type: 'string', length: 255)]
    private string $job = '';

    const JOBS = [
        'DEV' => 'dev',
        'CONSULTANT' => 'consultant',
        'PROJECT_MANAGER' => 'project manager'
    ];
    
    /**
     * @var string
     */
    #[ORM\Column(type: 'string', length: 255)]
    private string $password = '';

    /**
     * @var string|null
     */
    #[ORM\Column(type: 'string')]
    private string $headshot = '';

    /**
     * @var Collection
     */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Schedule::class, cascade: ['persist', 'remove'])]
    private Collection $schedule;

    /**
     * @var PasswordResetting|null
     */
    #[ORM\OneToOne(inversedBy: 'user', targetEntity: PasswordResetting::class, cascade: ['persist', 'remove'])]
    private ?PasswordResetting $PasswordResetting = null;

    /**
     * @var Collection
     */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity:Assignation::class)]
    private Collection $assignations;

    const ROLE_LIST = [
        'Admin' => 'ROLE_ADMIN',
        'Company leader' => 'ROLE_COMPANY_LEADER',
        'User' => 'ROLE_USER',
        'Team Manager' => 'ROLE_TEAM_MANAGER'
    ];

    /**
     * @var array
     */
    #[ORM\Column(type: 'json')]
    private array $roles = [];

    /**
     * @var Team|null
     */
    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Team $team = null;

    /**
     * @var null|Company
     */
    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Company $company = null;

    /**
     * @var Collection
     */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity:Absence::class)]
    private Collection $absences;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\ManyToMany(targetEntity: TchatRoom::class, mappedBy: 'title')]
    private Collection $tchatRooms;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Message::class)]
    private Collection $TchatMessage;

    /**
     * @var Collection<int, CalendarEvent>
     */
    #[ORM\ManyToMany(targetEntity: CalendarEvent::class, mappedBy: 'user')]
    #[ORM\OrderBy(["StartAt"=>"DESC"])] 
    private Collection $calendarEvents;

    /**
     * @return void
     */
    public function __construct()
    {
        $this->assignations = new ArrayCollection();
        $this->schedule = new ArrayCollection();
        $this->absences = new ArrayCollection();
        $this->schedule->add(new Schedule($this));
        $this->tchatRooms = new ArrayCollection();
        $this->TchatMessage = new ArrayCollection();
        $this->calendarEvents = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function getUserName(): string
    {
        return $this->userName;
    }

    /**
     * @param string $userName
     * @return void
     */
    public function setUserName(string $userName): void
    {
        $this->userName = $userName;
    }

    /**
     * @return string
     */
    public function getFirstName(): string
    {
        return $this->firstName;
    }

    /**
     * @param string $firstName
     * @return void
     */
    public function setFirstName(string $firstName): void
    {
        $this->firstName = $firstName;
    }

    /**
     * @return string
     */
    public function getLastName(): string
    {
        return $this->lastName;
    }

    /**
     * @param string $lastName
     * @return void
     */
    public function setLastName(string $lastName): void
    {
        $this->lastName = $lastName;
    }

    /**
     * @return string
     */
    public function getJob(): string
    {
        return $this->job;
    }

    /**
     * @param string $job
     * @return void
     */
    public function setJob(string $job): void
    {
        $this->job = $job;
    }

    /**
     * @return Collection
     */
    public function getSchedule(): Collection
    {
        return $this->schedule;
    }

    /**
     * @param Collection $schedule
     * @return void
     */
    public function setSchedule(Collection $schedule): void
    {
        $this->schedule = $schedule;
    }

    public function addSchedule(Schedule $schedule): self
    {
        $this->schedule->add($schedule);

        return $this;
    }

    /**
     * @return Collection
     */
    public function getAssignations(): Collection
    {
        return $this->assignations;
    }

    /**
     * @param Collection $assignations
     * @return void
     */
    public function setAssignations(Collection $assignations): void
    {
        $this->assignations = $assignations;
    }

    /**
     * @return string
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * @param string $email
     * @return void
     */
    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    /**
     * @return string
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    /**
     * @param string $password
     * @return void
     */
    public function setPassword(string $password): void
    {
        $this->password = $password;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param array $roles
     * @return $this
     */
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @param string $role
     * @return $this
     */
    public function addRole(string $role): static
    {
        $this->roles[] = $role;

        return $this;
    }

    /**
     * @param string $role
     * @return $this
     */
    public function removeRole(string $role)
    {
        unset($this->roles[array_search($role, $this->roles)]);

        return $this;
    }

    public function eraseCredentials(): void
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getUserIdentifier(): string
    {
        return $this->userName;
    }

    public function getLead(): ?Team
    {
        return $this->Lead;
    }

    public function setLead(?Team $Lead): static
    {
        $this->Lead = $Lead;

        return $this;
    }

    /**
     * @return Company|null
     */
    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(Company $company)
    {
        $this->company = $company;

        $company->addUser($this);

        return $this;
    }

    public function setTeam(?Team $team)
    {
        $this->team = $team;

        if($team) {
            $team->addUser($this);
        }
        
        return $this;
    }

    public function getTeam(): ?Team
    {
        return $this->team;
    }

    public function addAbsence(Absence $absence)
    {
        $absence->setUser($this);

        $this->absences->add($absence);
    }

    public function getAbsences()
    {
        return $this->absences;
    }

    public function isWorking(string $date, string $momentKey = 'AM')
    {
        
        foreach($this->absences as $key => $absence) {
            if ($absence->isOff($date, $momentKey)) {
                return $absence;
            }
        }

        $hour = '02:00';
        if ($momentKey == "AM") {
            $hour = '02:00';
        }

        try {
            $dateObject = DateTime::createFromFormat('d/m/Y h:i A', $date . " 02:00 " . $momentKey);
        } catch (\Throwable $th) {
            dump($th, $momentKey);
            die;
        }

        $schedule = $this->getScheduleByDate($dateObject);

        foreach($schedule->getDays() as $day) {
            if ($dateObject->format('l') === $day->getName()) {
                if ($momentKey === "AM") {
                    return $day->getMorning()->isWorking();
                } else {
                    return $day->getAfternoon()->isWorking();
                }
            }
        }

        return false;
    }

    public function getPasswordResetting()
    {
        return $this->PasswordResetting;
    }

    public function setPasswordResetting(PasswordResetting $passwordReset)
    {
        $this->PasswordResetting = $passwordReset;

Base/templates/User/Account/Absence.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Create Absence{% endtrans %}{% endblock %}

{% block breadcrumb %}
    {% set content = {
        'Home': 'app_index',
        'Account': 'my_account',
        'Create new absence': ''
        } %}

    {{ parent() }}
{% endblock %}

{% block body %}
    <div class="row pt-2 bg-light rounded py-4">
        <h1 class="text-secondary text-center col-12">{% trans %}Create an Absence{% endtrans %}</h1>
        <p class="text-muted text-center col-12">{% trans %}I want to create new absence{% endtrans %}.</p>
        <div class="px-4 col-12 col-lg-10 offset-lg-1">
            {{ form_start(form) }}
                <div class="row">
                    <div class='col-12'>
                        {{ form_row(form.type) }}
                    </div>

                    <div class='col-12'>
                        <p class="text-primary mt-2 mb-0 text-center">{% trans %}Dates are included in absence{% endtrans %}.</p>
                    </div>

                    <div class='col-12 col-md-5'>
                        {{ form_row(form.from) }}
                        {{ form_row(form.fromHour) }}
                    </div>

                    <div class='col-12 col-md-2 text-center'>
                        <div class='d-flex h-100 align-items-center justify-content-center'>
                            <i class="fas fa-arrow-right"></i>
                        </div>
                    </div>

                    <div class='col-12 col-md-5'>
                        {{ form_row(form.to) }}
                        {{ form_row(form.toHour) }}
                    </div>
                </div>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $( function() {
            var dateFormat = "dd/mm/yy",
            from = $( "#absence_from" )
                .datepicker({
                defaultDate: "+1w",
                dateFormat: dateFormat,
                changeMonth: true,
                numberOfMonths: 2,
                changeYear: true
                })
                .on( "change", function() {
                    console.log(getDate( this ));
                    to.datepicker( "option", "minDate", getDate( this ), "dateFormat", dateFormat);
                }),
            to = $( "#absence_to" ).datepicker({
                defaultDate: "+1w",
                changeMonth: true,
                dateFormat: dateFormat,
                numberOfMonths: 2,
                changeYear: true
            })
            .on( "change", function() {
                from.datepicker( "option", "maxDate", getDate( this ), "dateFormat", dateFormat);
            });
        
            function getDate( element ) {
                var date;
                try {
                    date = $.datepicker.parseDate( dateFormat, element.value );
                } catch( error ) {
                    date = null;
                }
        
            return date;
            }
        } );
    </script>
{% endblock %}

Base/templates/User/Account/company.html.twig
{% extends 'base.html.twig' %}

{% block title %}My Company{% endblock %}

{% block breadcrumb %}
    {% set content = {
        'Home': 'app_index',
        'Account': 'my_account',
        'My company': ''
        } %}

    {{ parent() }}
{% endblock %}

{% block body %}
    <div class="row w-100">
        <div class='col-12'>
            <h1 class='text-primary'>My Company</h1>
        </div>
        <div class='col-4 text-center'>
            <div class='bg-light w-100 position-sticky p-2' style='top: 80px;'>
                <h3 class='text-primary'>{{ app.user.username }}</h3>
                <p>{{ app.user.firstname }} {{ app.user.lastname }}</p>
                <p class='text-info'>{{ app.user.job }}</p>
            </div>
        </div>
        <div class="col-8">

            {{ form_start(form) }}
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

Base/templates/User/Account/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}My Account{% endtrans %}{% endblock %}

{% block breadcrumb %}
    {% set content = {
        'Home': 'app_index',
        'Account': 'my_account'
        } %}

    {{ parent() }}
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12"><h1 class="text-primary text-right">{% trans %}My Account{% endtrans %}</h1></div>
        {{ block('Main_informations') }}
    </div>
{% endblock %}

{% block Main_informations %}
    <div class="col-lg-4 col-12">
        <div class="sticky-top bg-light rounded p-4 border" style="z-index: 10;">
            {% if not app.user.headshot %}
                <div class="border mx-auto d-flex text-muted mx-auto align-items-center justify-content-center profile">
                    <i class="far fa-user-circle fa-2xl"></i>
                </div> 
            {% else %}
                <div class="profile border mx-auto" style="">
                    <img src="{{ asset('uploads/brochures') }}/{{ app.user.headshot }}" title="{% trans %}Logo profile{% endtrans %}">
                </div>
            {% endif %}
            <p class="text-right mb-0"><a href="{{ path('user_update') }}" class="btn btn-light rounded-circle"><i class="fas fa-pen"></i></a></p>
            <h2 class="text-primary text-center">{% trans with {'%name%': app.user.username} %}Logged as %name%{% endtrans %}</h2>
            {% if app.user.roles|length > 0 %}
                <div class="d-flex flex-wrap justify-content-around pb-2">
                    {% for role in app.user.roles %}
                        <p class="px-2 py-1 text-muted mx-1 mb-1">{{ role|trans|replace({'_': ' '})|replace({'ROLE': ''})|lower }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <h3 class='mb-0  text-center'>{{ app.user.firstName }} {{ app.user.lastName }}</h3>
            <p class='mb-0 font-weight-bold text-center {% if not app.user.email %}text-muted{% endif %}'>{{ app.user.email ?: "Empty email"|trans }}</p>
            
            <p class='mb-0 text-center   border-top pt-2 mt-2'>
                {% if app.user.team %}
                    <a href="#team_part" class="btn btn-link">{% trans %}My team{% endtrans %} <span class="font-weight-bold">{{ app.user.team.name }}</span></a><br>
                {% endif %}
                <a href="#calendar_part" class="btn btn-link">{% trans %}My calendar{% endtrans %}</a>
                <br>
                <a href="#shedules_part" class="btn btn-link">{% trans %}My schedules{% endtrans %}</a>
                <br>
                <a href="#absences_part" class="btn btn-link">{% trans %}My absences{% endtrans %}</a>
            </p>           
        </div>
    </div>

    <div class="col-lg-8 col-12 pt-lg-4">
        <h2 class="text-secondary line-secondary mb-3" id="calendar_part">
            <span>{% trans %}My calendar{% endtrans %}</span>
        </h2>
        {% include "Calendar/view.html.twig" with {'users': [app.user], 'showUsers': false} %}

        <h2 class="text-secondary line-secondary mb-3 d-flex justify-content-between" id="shedules_part">
            <span>{% trans %}My schedules{% endtrans %}</span>
            <a href="{{ path('new_schedule') }}" class="btn btn-light"><i class="fas fa-pen mr-2"></i>{% trans %}Modify{% endtrans %}</a>
        </h2>

        {% include "User/Account/scheduleView.html.twig" with {'user': app.user} %}

        <h2 class="text-secondary line-secondary mb-3 mt-2 d-flex justify-content-between" id="absences_part">
            <span>{% trans %}My absences{% endtrans %}</span>
            <a href="{{ path('new_absence') }}" class="btn btn-light">{% trans %}Create absence{% endtrans %}</a>
        </h2>
        <div class="">

            <div class="row">
            {% set future = false %}
                {% for absence in app.user.absences %}
                    {% if absence.to > 'now'|dateType %}
                        {% set future = true %}
                        <div class='col-4'>
                            <a href="{{ path('absence_update', {'id': absence.id}) }}" class="btn btn-light btn-block">
                                <p class="text-center text-primary font-weight-bold">{{ absence.type }}</p>
                                <p class="text-dark">{{ absence.from|date('d/m/Y') }} <i class="fas fa-arrow-right"></i> {{ absence.to|date('d/m/Y') }}</p>
                            </a>
                        </div>
                    {% endif %}
                {% endfor %}

                <div class="col-12">
                    {% if app.user.absences|length == 0 %}
                        <h3 class="text-muted text-center col-12">{% trans %}No absence created{% endtrans %}</h3>
                    {% elseif not future %}
                        <h3 class="text-muted text-center col-12">{% trans %}No future absence{% endtrans %}</h3>
                    {% endif %}
                </div>

                <div class="collapse col-12" id="allAbsences">
                    <div class="card card-body py-2 bg-light">
                        <p class="text-right">{% trans %}All Absences{% endtrans %}</p>
                        {% for absence in app.user.absences %}
                            <div class="row border bg-white mb-1 py-2">
                                <div class='col-8'>
                                    <p class="text-dark mb-0">{{ absence.from|date('d/m/Y') }} <i class="fas fa-arrow-right"></i> {{ absence.to|date('d/m/Y') }}</p>
                                </div>

                                <div class='col-4'>
                                    <p class="text-center text-primary font-weight-bold mb-0">{{ absence.type }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>

                <div class="col-12 text-right">
                    {% if app.user.absences|length > 0 %}
                        <div class="col-12 text-right">
                            <button role="button" class="btn btn-link" data-toggle="collapse" expanded-txt="{% trans %}Hide{% endtrans %}" collapsed-txt="{% trans %}See all{% endtrans %}" data-target="#allAbsences" aria-expanded="false" aria-controls="allAbsences">{% trans %}See all{% endtrans %}</button>
                        </div>
                    {% endif %}
                    
                </div>
            </div>
            
        </div>

        {% if app.user.team %}
            <h2 class="text-secondary line-secondary mb-3 mt-2 d-flex justify-content-between" id="team_part">
                <span>{% trans with {'%name%': app.user.team.name|upper} %}My Team %name%{% endtrans %}</span>
            </h2>

            <div class="px-4">
                <p class="text-right">{% trans %}Leader{% endtrans %} : <span class="font-weight-bold text-primary">{{ app.user.team.lead.userName }}</span></p>
                {% for user in app.user.team.users %}
                    <div class='row rounded bg-light'>
                        <div class="col-lg-2 col-6 p-2">
                            <p class="mb-0 text-primary font-weight-bold">{{ user.userName }}</p>
                        </div>

                        <div class="col-lg-4 col-6 p-2">
                            <p class="mb-0">{{ user.firstName }} {{ user.lastName }}</p>
                        </div>
                        <div class="col-4 col-lg-4 p-2">
                            <p class="mb-0">{{ user.email }}</p>
                        </div>

                        <div class="col-6 col-lg-2 text-center p-1">
                            <p class="mb-0 text-dark font-weight-bold font-italic p-1">{{ user.job }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        
    </div>
{% endblock %}