Base/src/Entity/CalendarEvent.php
<?php

namespace App\Entity;

use App\Entity\User\User;
use App\Repository\CalendarEventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CalendarEventRepository::class)]
class CalendarEvent
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $StartAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $endAt = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adress = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'calendarEvents')]
    private Collection $user;

    public function __construct()
    {
        $this->user = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartAt(): ?\DateTimeImmutable
    {
        return $this->StartAt;
    }

    public function setStartAt(\DateTimeImmutable $StartAt): static
    {
        $this->StartAt = $StartAt;

        return $this;
    }

    public function getEndAt(): ?\DateTimeImmutable
    {
        return $this->endAt;
    }

    public function setEndAt(\DateTimeImmutable $endAt): static
    {
        $this->endAt = $endAt;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(?string $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(User $user): static
    {
        if (!$this->user->contains($user)) {
            $this->user->add($user);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        $this->user->removeElement($user);

        return $this;
    }
}

Base/src/Form/CalendarEventType.php
<?php

namespace App\Form;

use App\Entity\CalendarEvent;
use App\Entity\Company;
use App\Entity\User\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Doctrine\ORM\QueryBuilder;
use App\Repository\UserRepository;

class CalendarEventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $company = $options['company'];

        $builder
            ->add('StartAt', DateTimeType::class, [
                'date_widget' => 'single_text',
                'time_widget' => 'choice',
                'hours' => ['07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23'],
                'minutes' => [00, 15, 30, 45 ],
                'time_label' => 'Hour',
                'with_minutes' => true
            ])
            ->add('endAt', DateTimeType::class, [
                'date_widget' => 'single_text',
                'time_widget' => 'choice',
                'hours' => ['07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23'],
                'minutes' => [00, 15, 30, 45 ],
                'with_minutes' => true
            ])
            ->add('name')
            ->add('description')
            ->add('adress')
            ->add('user', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'email',
                'label' => 'participant',
                "expanded" => true,
                'multiple' => true,
                'query_builder' => function (UserRepository $er) use($company): QueryBuilder {
                    return $er->createQuery($company->getId());
                }
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CalendarEvent::class,
            'company' => null
        ]);
    }
}

Base/src/Controller/CalendarEventController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\CalendarEvent;
use App\Form\CalendarEventType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use App\Controller\BaseController;

#[Route('/Event')]
final class CalendarEventController extends BaseController
{
    #[Route('/', name: 'app_calendar_event')]
    public function index(): Response
    {
        return $this->render('calendar_event/index.html.twig', []);
    }

    #[Route('/{id}/update', name: 'app_calendar_event_update')]
    public function update(CalendarEvent $id, Request $request): Response
    {
        $form = $this->getEventForm($id, $request, 'Update');

        if (!$form) {
            return $this->redirectToRoute('app_calendar_event');
        }

        return $this->render('calendar_event/update.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/new', name: 'app_calendar_event_create')]
    public function create(Request $request): Response
    {
        $event = new CalendarEvent();

        $form = $this->getEventForm($event, $request);

        if (!$form) {
            return $this->redirectToRoute('app_calendar_event');
        }

        return $this->render('calendar_event/update.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/{id}/delete', name: 'app_calendar_event_delete')]
    public function delete(Request $request, CalendarEvent $id)
    {
        $entityManager = $this->entityManager;

        $entityManager->remove($id);

        $entityManager->flush();

        $this->addFlash('success', 'Event deleted');

        return $this->redirectToRoute('app_calendar_event');
    }

    private function getEventForm(CalendarEvent $event, Request $request, string $button = "Create")
    {
        $form = $this->createForm(CalendarEventType::class, $event, ['company' => $this->getUser()->getCompany()]);

        $form
            ->add('create', SubmitType::class, [
                'label' => $button,
                'attr' => [
                    'class' => 'btn btn-primary'
                ]
            ])
        ;

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            if($event->getStartAt() > $event->getEndAt()) {
                $this->addFlash('danger', 'Start date can\t be greater than end date.');
            } else {
                $entityManager = $this->entityManager;

                $entityManager->persist($form->getData());
                $entityManager->flush();

                if ($button === "Create") {
                    $this->addFlash('success', 'Event created.');
                } elseif ($button === "Update") {
                    # code...
                } {
                    $this->addFlash('success', 'Event updated.');
                }

                return false;
            }
        }

        return $form;
    }
}

Base/templates/calendar_event/EventCalendar.html.twig
<!-- Events carousel -->
<div id="event-slider" class="carousel slide">
    <div class="carousel-inner">
        {% for year, months in weeks %}
            {% for month, w in months %}
                {% for wNumber, days in w %}
                    <div class="carousel-item {% if wNumber == 'now'|date('W') %}active{% endif %}">
                        <div class='row'>
                            {% if withList is defined and withList == true %}
                                <div class='col-md-5 offset-md-1'>
                                    {% for dayNum, events in days %}
                                        {% set date = (dayNum ~ '-' ~ month ~ '-' ~ year)|dateType('d-F-Y H:i') %}
                                        <p class="mb-0 text-muted fst-italic"><small>{{ date|date('d F') }}</small></p>
                                        {% include 'calendar_event/calendar_list.html.twig' with {'events': events} %}
                                    {% endfor %}

                                    <div class="text-end mt-2">
                                        <a href="{{ path('app_calendar_event_create') }}" class="btn btn-primary rounded-circle" style="">
                                            <i class="fa-solid fa-plus"></i>
                                        </a>
                                    </div>
                                </div>
                            {% endif %}
                            
                            <div class='{% if withList is defined and withList == true %}col-md-5{% else %}col-md-10 offset-md-1{% endif %}'>
                                <div class="border">
                                    <div class="bg-secondary py-2 text-center text-secondary-reverse">
                                        <h3 class="mb-0">{{ month|trans }}</h3>
                                        <p class="mb-0">{% trans with {'%number%': wNumber} %}Week number %number%{% endtrans %}</p>
                                    </div>

                                    <div class="grid-col-8 grid">
                                        <p class="mb-0 text-center">{% trans %}Hour{% endtrans %}</p>

                                        {% for dayName, e in days %}
                                            {% set date = (dayName ~ '-' ~ month ~ '-' ~ year)|dateType('d-F-Y H:i') %}
                                            <p class="mb-0 text-center">{{ date|date('D') }}</p>
                                        {% endfor %}

                                        {% for hour in 7..20 %}
                                            {% for time in ['00', '30'] %}
                                                <section class="mb-0 text-center {% if time == '30' %}border-bottom{% else %}border-bottom border-top{% endif %}">
                                                    <p class="mb-0">{{ hour }}:{{ time }}</p>
                                                </section>
                                                
                                                
                                                {% for day, events in days %}
                                                    <p class="mb-0 border-end border-start d-flex {% if time == '30' %}border-bottom{% else %}border-bottom border-top{% endif %}">
                                                        {% set date = (day ~ ' ' ~ month ~ ' ' ~ year)|dateType('d F Y H:i', hour, time) %}
                                                        {% for event in events %}
                                                            {% if date >= event.startAt and date <= event.endAt %}
                                                                <span calendar-event="{{ event.id }}" class="bg-primary hover py-1 px-1">
                                                                    &nbsp
                                                                </span>
                                                            {% endif %}
                                                        {% endfor %}
                                                    </p>
                                                {% endfor %}
                                                    
                                            {% endfor %}
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endfor %}
        {% endfor %}
    </div>

    <button class="carousel-control-prev btn btn-outline-dark" type="button" data-bs-target="#event-slider" data-bs-slide="prev">
        <i class="fa-solid fa-angle-left fa-lg"></i>
    </button>
    <button class="carousel-control-next btn btn-outline-dark" type="button" data-bs-target="#event-slider" data-bs-slide="next">
        <i class="fa-solid fa-angle-right fa-lg"></i>
    </button>

    {% if withList is not defined or withList == false %}
        <a href="{{ path('app_calendar_event_create') }}" class="btn btn-primary rounded-circle position-absolute" style="bottom: -2rem; right: 50px;">
            <i class="fa-solid fa-plus"></i>
        </a>
    {% endif %}
</div>

Base/templates/calendar_event/calendar_list.html.twig
{% for event in events %}
    <div class="rounded px-2 py-2 mb-2 border bg-light row align-items-center justify-content-center" event-list="{{ event.id }}">
        <div class="col-md-8">
            <div class="d-flex align-items-baseline">
                <h4 class="mb-0">
                    {{ event.name }}
                </h4>

                {% if event.description|length > 0 %}
                    <small>
                        <a class="btn btn-link btn-sm" data-bs-toggle="collapse" href="#event-description-{{ event.id }}" role="button" aria-expanded="false" aria-controls="event-description">{% trans %}More{% endtrans %}...</a>
                    </small>
                {% endif %}
            </div>
            {% if event.description|length > 0 %}
                <p class="mb-0 text-muted">
                    <small class="collapse" id="event-description-{{ event.id }}">{{ event.description }}</small>
                </p>  
            {% endif %}
            <p class="mb-0">
                <small>
                    {% trans with {'%from%': event.startAt|date('d/m/Y H:i'), '%to%': event.endAt|date('d/m/Y H:i')} %}From %from% to %to%{% endtrans %}
                </small>
            </p>
        </div>

        <div class="col-md-4">
            <p class="mb-0 text-end">
                <a class="btn btn-light rounded-circle" href="{{ path('app_calendar_event_update', {'id': event.id}) }}"><i class="fa-solid fa-pen"></i></a>
                <a class="btn btn-outline-dark rounded-circle" href="{{ path('app_calendar_event_delete', {'id': event.id}) }}"><i class="fa-solid fa-trash-can"></i></a>
            </p>
        </div>
    </div>
{% endfor %}

{% if events|length == 0 %}
    <p class="text-muted text-center">{% trans %}No event.{% endtrans %}</p>
{% endif %}

Base/templates/calendar_event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}My events{% endtrans %}{% endblock %}

{% block breadcrumb %}
    {% set content = {
        'Home': 'app_index',
        'Events': 'app_calendar_event'
        } %}

    {{ parent() }}
{% endblock %}

{% block body %}
    {% set weeks = weeks('now'|date('d-m-Y'), app.user) %}
    <div class="">
        <div class="d-flex justify-content-between align-items-center">
            <h1 class="text-primary">{% trans %}My events{% endtrans %}</h1>
        </div>

        {% include 'calendar_event/EventCalendar.html.twig' with {'weeks': weeks, 'withList': true} %}
    </div>
{% endblock %}

Base/templates/calendar_event/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}My Events form{% endtrans %}{% endblock %}

{% block body %}
    <div class="p-5">
        <div class="border bg-light p-3">

            {{ form_start(form) }}
                {{ form_row(form.name) }}
                {{ form_row(form.description) }}
                {{ form_row(form.adress) }}

                <div class="row align-items-center">
                    <div class="col-md-4">
                        {{ form_row(form.StartAt) }}
                    </div>

                    <div class="col-md-4 text-center">
                        <i class="fa-solid fa-arrow-right"></i>
                    </div>

                    <div class="col-md-4">
                        {{ form_row(form.endAt) }}
                    </div>
                </div>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}